### ISSUE TITLE
Training GDN

### ISSUE THREAD

**Issue by peerschuett** [wagner-d/TimeSeAD#11]
Hi,
thank you for your paper and the published code! I want to use your code to train GDN on my own hardware and reproduce your results from the paper. I already have all the datasets, but I am not sure how to best execute the training now. Can I just call https://github.com/wagner-d/TimeSeAD/blob/master/timesead_experiments/prediction/train_gdn.py and it will produce me the results I want, or do I need to adapt https://github.com/wagner-d/TimeSeAD/blob/master/timesead_experiments/train_model_template.py ?
Thanks a lot!

Best regards
Peer

**Comment by batman-nair** [comment]
Hi @peerschuett, running train_gdn.py trains a GDN model using the default parameters and datasets. You can change the parameters for the run by specifying it through CLI options. 
For example, to train on SMD dataset server id 1, `python timesead_experiments/prediction/train_gdn.py with dataset.name=SMDDataset dataset.ds_args.server_id=0`

The results in the paper are cross-validation results by doing grid search on the datasets. The configurations for the grid search are saved in YML files in the experiment_configs folder. 
A sample run, `python timesead_experiments/grid_search.py with experiment_configs/smd/prediction/train_gdn.yml dataset.ds_args.server_id=1 training_param_updates.dataset.ds_args.server_id=1`

Hope this answers your questions

**Comment by peerschuett** [comment]
Thanks a lot for the feedback! I will try that :)

**Comment by peerschuett** [comment]
It works, thanks!
